[package]
name = "adcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
volatile = "0.4.5"
log = "0.4.16"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
hex = "0.4.3"